[package]
edition = "2018"
name = "bandwhichd-agent"
description = "Publish current network utilization"
version = "0.21.0"
homepage = "https://github.com/neuland/bandwhichd-agent"
repository = "https://github.com/neuland/bandwhichd-agent"
readme = "README.md"
authors = [
    "Aram Drevekenin <aram@poor.dev>",
    "Eduardo Toledo <etoledom@icloud.com>",
    "Eduardo Broto <ebroto@tutanota.com>",
    "Kelvin Zhang <zhangxp1998@gmail.com>",
    "Brooks Rady <b.j.rady@gmail.com>",
    "Michel Zimmer <michel.zimmer@neuland-bfi.de>"
]
keywords = ["networking", "utilization", "agent"]
categories = ["network-programming"]
license = "MIT"
exclude = ["src/tests/*"]

[dependencies]
pnet = "0.26.0"
ipnetwork = "0.16.0"
tui = { version = "0.12", default-features = false, features = ["crossterm"] }
crossterm = "0.17.7"
structopt = "0.3"
failure = "0.1.6"
chrono = "0.4"
regex = "1.3.1"
lazy_static = "1.4.0"
tokio = { version = "0.2", features = ["rt-core", "sync"] }
trust-dns-resolver = "0.18.1"
async-trait = "0.1.21"
unicode-width = "0.1.8"
resolv-conf = "0.7.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["serde-well-known"] }

[target.'cfg(target_os="windows")'.dependencies]
netstat2 = "0.9.0"
sysinfo = "0.15.1"

[target.'cfg(target_os="linux")'.dependencies]
procfs = "0.7.4"

[dev-dependencies]
insta = "0.12.0"
pnet_base = "0.26.0"
cargo-insta = "0.11.0"
packet-builder = "0.5.0"
regex = "1"

[target.'cfg(target_os="windows")'.build-dependencies]
http_req = "0.7.0"
zip = "0.5.6"

[patch.crates-io]
resolv-conf = { git = 'https://github.com/tailhook/resolv-conf', rev = '83c0f25ebcb0615550488692c5213ca1ae4acd8f' }
